package com.example.usertracker

object TrackerActions {
    val SEND_DEVICEINFO = "SEND_DEVICEINFO"
    val APP_OPEN = "APP_OPEN"
    val APP_CLOSE = "APP_CLOSE"
    val NETWORK_REQ_RETRIES = "NETWORK_REQ_RETRIES"
    val APP_DATA = "APP_DATA"
    val NOTIFICATION_DISMISS = "NOTIFICATION_DISMISS"
    val NOTIFICATION_CLICK = "NOTIFICATION_CLICK"
    val SERVER_STATUS = "SERVER_STATUS"
    val SEND_SESSION = "SEND_SESSION"
}